apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
    - port: 6379 # same as the containerport in the redis pod 
      targetPort: 6379
  selector:
    # this part is the same as the part under the labels section in the redis pod definition fiel.
    name: redis-pod
    app: demo-voting-app
