apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80 
      targetPort: 80 
      nodePort: 30004
  selector:
    # this part is the same as the part under the labels section in the voting pod definition file.
    name: voting-app-pod
    app: demo-voting-app
